# 全局配置
system:
  app:
    # 设定模式(debug/release/test,正式版改为release)
    mode: debug
    host: "127.0.0.1"
    port: 8089
    # 是否初始化数据(没有初始数据时使用, 已发布正式版改为false)
    init-data: false
  log:
    level: "debug"  #debug,info,warn,error,dpanic,panic,fatal
    logPath: "./debug.log"  #"/opt/ops_tool/debug.log"
    compress: true #是否压缩处理
    maxSize: 200 #文件大小限制,单位MB
    maxBackups: 7 #文件保留天数
    maxAge: 30 #最大保留日志文件数量
  # 默认mysql账号密码，如果有需要更改请一并更改dockerfile
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "123456"
    dbname: "dingding"
    max_open_cons: 10
    max_idle_cons: 20

# jenkinsDingTalk工具配置
jenkinsDingTalk:
  jenkins:
    name: ""
    password: ""
  dingDing:
    default_notifier:
    token: ""

